# MecâniQA — Encontro 1: Importação e Inspeção Inicial

In [1]:
import pandas as pd

# Importação do dataset
df = pd.read_csv("mecaniqa_dataset.csv")

print("Dataset importado com sucesso!")
df.head()

Dataset importado com sucesso!

         Data  Trocas_Oleo  Manutencao_Motor
0  2024-01-01         11.0               2.0
1  2024-01-02          9.0               4.0
2  2024-01-03         12.0               1.0
3  2024-01-04         15.0               8.0
4  2024-01-05         25.0              10.0

In [2]:
# Remove possíveis espaços dos nomes das colunas
df.columns = df.columns.str.strip()

# Converte a coluna Data para datetime
df["Data"] = pd.to_datetime(
    df["Data"],
    format="%Y-%m-%d",
    errors="raise"
)

# Define Data como índice e organiza cronologicamente
df = df.set_index("Data")
df = df.sort_index()

print("Indexação temporal concluída!")
df.head()

Indexação temporal concluída!

            Trocas_Oleo  Manutencao_Motor
Data
2024-01-01         11.0               2.0
2024-01-02          9.0               4.0
2024-01-03         12.0               1.0
2024-01-04         15.0               8.0
2024-01-05         25.0              10.0

In [3]:
df.info()

<class 'pandas.DataFrame'>
DatetimeIndex: 731 entries, 2024-01-01 to 2025-12-31
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Trocas_Oleo       725 non-null    float64
 1   Manutencao_Motor  728 non-null    float64
dtypes: float64(2)
memory usage: 17.1 KB

In [4]:
print("Quantidade de registros:", df.shape[0])
print("Quantidade de colunas:", df.shape[1])
print("Atributos principais:", [df.index.name] + df.columns.tolist())
print("Tipo do índice:", type(df.index))

Quantidade de registros: 731
Quantidade de colunas: 2
Atributos principais: ['Data', 'Trocas_Oleo', 'Manutencao_Motor']
Tipo do índice: <class 'pandas.DatetimeIndex'>

In [5]:
print("Quantidade de datas inválidas:", df.index.isna().sum())
print("Data inicial:", df.index.min())
print("Data final:", df.index.max())

Quantidade de datas inválidas: 0
Data inicial: 2024-01-01 00:00:00
Data final: 2025-12-31 00:00:00

In [6]:
print("Valores ausentes por atributo:")
print(df.isnull().sum())

Valores ausentes por atributo:
Trocas_Oleo         6
Manutencao_Motor    3
dtype: int64

In [7]:
df.describe()

       Trocas_Oleo  Manutencao_Motor
count   725.000000        728.000000
mean     26.020690         10.179945
std      11.620655          5.419338
min       0.000000         -2.000000
25%      18.000000          7.000000
50%      26.000000         10.000000
75%      33.000000         13.000000
max     150.000000         85.000000